AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: sealigths-lambda-example-prod
Globals:
  Function:
    Timeout: 30

Resources:
  Function1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:  function_1/
      Handler: app.lambda_handler
      Runtime: python3.11
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /function1
            Method: get
  Function2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:  function_2/
      Handler: app.lambda_handler
      Runtime: python3.11
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /function2
            Method: get
Outputs:
  Function1:
    Description: "Sealights Lambda Function1 ARN"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/function1/"
  Function2:
    Description: "Sealights Lambda Function2 ARN"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/function2/"